apiVersion: v1
kind: Secret
metadata:
    name: immich-backup-secret
    namespace: default
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:c9X5Uw6/4Toal4IhKc7da1eK2tM=,iv:DrtKD/Q6dtPjL+/xAunsgGX5R5Q8SOqp384xx/YF0yE=,tag:L3rI6suGWDWWxrnylM4Wgg==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:A+ElNIanQ38lxb0yHX0QqoV+69IaMQzhvlkQ/+xjUQ0UhvuAeU0Qng==,iv:5M3wWVuAyvjjirUQ7/gTslfORInv89f8Xq21VNTVMK4=,tag:XkURsN45SZHrKfjUscHe/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l6hn6tqssp82508dcmyrg0dcxrzjv04m0xc7apcffly02y9prqlsj3zmt2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib3JoRldSWFBxMEdmUmpv
            akpsb1JlVlRNdTBSUXdoQWMzNTJCdjVObkVjCmFEbng3Y0U2WitROXRiNnNYaDdj
            dzdiSVMyQzJuMlpUek5oRklGZ0hOL00KLS0tIG5KUk40b2JReUE5MkdLQWNzMWto
            TjU0QXc3SUJyK3ZFSStEaCsyT0FMajQKzbnMAEVU9KQGqMg0Yn7M1BRQy7cuT2H4
            M+RXNw862JTII8xft68a07+RZci3Dj9wrNVQ7a+Vhd8pZxPNu2xcug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-10T08:01:54Z"
    mac: ENC[AES256_GCM,data:yJOFdvgJuuFFtWaJ9eQqPQrpjBQLIp297QLn4GLK3HI6N7D1g8ONFGQxTCGYgfo/MG68PFYG0wJK3rOHRKRmc1XxDDd+Uf+mwmgAB4F5S1groPvI/O0CH/1v9H0YYtxfxpK4II/iD2Ec2a1yO4zdg8gH/qhVH+KoCy/cjw/uqiQ=,iv:9Xlif+WtHML/Bz9JhcR0CrGHsqiIcpJpxmljuA1jPRg=,tag:GHKaIxkYg/j0rb1sAXAZvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
