---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-ml-pv
spec:
  storageClassName: nfs-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data
    server: nas01.localdomain
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
spec:
  storageClassName: nfs-data
  capacity:
    storage: 350Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/immich
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-pvc
spec:
  storageClassName: nfs-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
spec:
  storageClassName: nfs-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi